#使用的后台
server.lang = jsp #可以是php jsp net

#使用的主题
theme = default

#使用的语言包

#以下是可配置的插件,如果不想合并某个插件，在plugin前加#,类似#plugin=xxxx，那合并的版本中将不会有该插件

#加粗,斜体,上标,下标
plugin=basestyle

#锚点
plugin=anchor

#悬浮工具栏
plugin=autofloat

#编辑框自动长高
plugin=autoheight

